#这个文件可以是空的
from .SrcLoaderBase import BaseParameterSrcLoder,BaseSrcLoader,BaseResultSrcLoder
from .SrcLoaderBase import ResultSrcLoder

from .SrcLoaderImp import ParameterSrcLoderTxt,SrcLoaderTxt
from .SrcLoaderImp import ParameterSrcLoderCSV,SrcLoaderCSV
from .SrcLoaderImp import ParameterLoderSrcMD,SrcLoaderMD
from .SrcLoaderImp import ParameterSrcLoderJSON,SrcLoaderJSON
from .SrcLoaderImp import ParameterSrcLoderURL,SrcLoaderURL
from .SrcLoaderImp import ParameterSrcLoderImageJpgPng,SrcLoaderImageJpgPng
from .SrcLoaderImp import ParameterSrcLoderImageOCR,SrcLoaderImageOCR
from .SrcLoaderImp import ParameterSrcLoderImageOCRModel,SrcLoaderImageOCRModel
from .SrcLoaderImp import ParameterSrcLoderMHTML,SrcLoaderMHTML
from .SrcLoaderImp import ParameterSrcLoderHTML,SrcLoaderHTML
from .SrcLoaderImp import ParameterSrcLoderDocDocx,SrcLoaderDocDocx
from .SrcLoaderImp import ParameterSrcLoderImageContent,SrcLoaderImageContent
from .SrcLoaderImp import ParameterSrcLoderXlsXlsx,SrcLoaderXlsXlsx
from .SrcLoaderImp import ParameterSrcLoderPDFModel,SrcLoaderPDFModel
from .SrcLoaderImp import ParameterSrcLoderPDF,SrcLoaderPDF
from .SrcLoaderImp import ParameterSrcLoderPPT,SrcLoaderPPT
